# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentzapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fbid',
            field=models.CharField(blank=True, max_length=140, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='accesstoken',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='account',
            name='displayname',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
