# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentzapp', '0004_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accesstoken',
            field=models.CharField(max_length=750),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
