# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentzapp', '0005_auto_20170915_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likescount',
            field=models.IntegerField(default=0),
        ),
    ]
