# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentzapp', '0006_blogpost_likescount'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(to='studentzapp.Like'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentzapp.BlogPost'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='ownername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owname', to=settings.AUTH_USER_MODEL),
        ),
    ]
