# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentzapp', '0007_auto_20170915_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='likes',
            field=models.ManyToManyField(null=True, to='studentzapp.Like'),
        ),
    ]
