# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentzapp', '0009_auto_20170915_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
